# -*- coding: utf-8 -*-
"""系统收尾两周交付计划 -> PDF (Report route: ReportLab body + cover_render cover + pypdf merge)."""
import os, sys

PDF_SKILL_DIR = "/home/longxiang/.zcode/cli/plugins/cache/zcode-plugins-official/document-skills/0.1.4/skills/pdf"
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, "scripts"))

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    KeepTogether, CondPageBreak, HRFlowable,
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ── Fonts (host probe: only DroidSansFallbackFull is TrueType-outlined CJK) ──
pdfmetrics.registerFont(TTFont("WQY", "/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc", subfontIndex=0))
registerFontFamily("WQY", normal="WQY", bold="WQY", italic="WQY", boldItalic="WQY")

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
# Intent: neutral | Mode: minimal | Harmony: split_complementary
ACCENT       = colors.HexColor('#278eb0')
TEXT_PRIMARY = colors.HexColor('#1d1f20')
TEXT_MUTED   = colors.HexColor('#6e767a')
BG_SURFACE   = colors.HexColor('#d4dade')
BG_PAGE      = colors.HexColor('#eef0f1')
TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

OUT_DIR = "/tmp/wrapup_pdf"
BODY_PDF = os.path.join(OUT_DIR, "body.pdf")
COVER_PDF = os.path.join(OUT_DIR, "cover.pdf")
FINAL_PDF = "/home/longxiang/MiroThinker/docs/plans/2026-09-07-system-wrapup-delivery-plan.pdf"

PAGE_W, PAGE_H = A4
LM = RM = 2.0 * cm
TM, BM = 2.2 * cm, 2.0 * cm
AVAIL_W = PAGE_W - LM - RM
MAX_KEEP_HEIGHT = PAGE_H * 0.4

# ── Styles ──
h1 = ParagraphStyle("H1", fontName="WQY", fontSize=16, leading=24,
                    textColor=ACCENT, spaceBefore=18, spaceAfter=8, wordWrap="CJK")
h2 = ParagraphStyle("H2", fontName="WQY", fontSize=13, leading=20,
                    textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=6, wordWrap="CJK")
h3 = ParagraphStyle("H3", fontName="WQY", fontSize=11, leading=17,
                    textColor=ACCENT, spaceBefore=10, spaceAfter=4, wordWrap="CJK")
body = ParagraphStyle("Body", fontName="WQY", fontSize=10.5, leading=17,
                      textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap="CJK",
                      firstLineIndent=21, spaceAfter=6)
body_ni = ParagraphStyle("BodyNI", parent=body, firstLineIndent=0)
bullet = ParagraphStyle("Bullet", fontName="WQY", fontSize=10.5, leading=17,
                        textColor=TEXT_PRIMARY, leftIndent=16, wordWrap="CJK",
                        spaceBefore=1, spaceAfter=3)
th = ParagraphStyle("TH", fontName="WQY", fontSize=10, leading=15,
                    textColor=TABLE_HEADER_TEXT, alignment=TA_CENTER, wordWrap="CJK")
tc = ParagraphStyle("TC", fontName="WQY", fontSize=9.5, leading=15,
                    textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap="CJK")
tc_c = ParagraphStyle("TCC", parent=tc, alignment=TA_CENTER)

def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        w, h = el.wrap(AVAIL_W, PAGE_H)
        total_h += h
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def make_table(header, rows, ratios, col_styles=None):
    data = [[Paragraph("<b>%s</b>" % c, th) for c in header]]
    for r in rows:
        data.append([Paragraph(c, (col_styles[i] if col_styles else tc)) for i, c in enumerate(r)])
    widths = [x * AVAIL_W * 0.98 for x in ratios]
    assert sum(widths) <= AVAIL_W + 0.5
    t = Table(data, colWidths=widths, hAlign="CENTER", repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]
    for i in range(1, len(data)):
        style.append(("BACKGROUND", (0, i), (-1, i), TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD))
    t.setStyle(TableStyle(style))
    return t

def page_deco(canvas, doc):
    canvas.saveState()
    # header
    canvas.setFont("WQY", 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LM, PAGE_H - 1.3 * cm, "系统收尾两周交付计划")
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(LM, PAGE_H - 1.55 * cm, PAGE_W - RM, PAGE_H - 1.55 * cm)
    # footer
    canvas.setStrokeColor(TEXT_MUTED)
    canvas.setLineWidth(0.3)
    canvas.line(LM, 1.4 * cm, PAGE_W - RM, 1.4 * cm)
    canvas.setFont("WQY", 7.5)
    canvas.drawString(LM, 1.0 * cm, "科创数据平台 · 系统收尾专项")
    canvas.drawRightString(PAGE_W - RM, 1.0 * cm, "第 %d 页" % doc.page)
    canvas.restoreState()

story = []

# ══ 一、里程碑总览 ══
story.extend(safe_keep_together([
    Paragraph("一、里程碑总览", h1),
    Paragraph("执行窗口 9 月 8 日（周二）开工至 9 月 21 日（周一）完成，共 10 个工作日；五个里程碑逐项交付。", body_ni),
]))
story.append(Spacer(1, 12))
ms_rows = [
    ["M1", "9/9（周三）", "Milvus 死锁修复；配置中心上线（系统状态、数据新鲜度、采集配置、key 健康检查）"],
    ["M2", "9/11（周五）", "任务运行面 + “立即采集”按钮；用户会话审计增强（身份维度、时间过滤、导出、统计）"],
    ["M3", "9/15（周二）", "周期采集试运行（cron、配额、熔断）；XLSX 上传导入 + seed 管理上线"],
    ["M4", "9/17（周四）", "管理面全部完成（质量问题页、教授工作台、旧前端退役）；首次一键数据发布演练成功（含回滚验证）"],
    ["M5", "9/21（周一）", "采集、发布、检索端到端验收；运维手册与现场迁移素材交付"],
]
story.append(make_table(["里程碑", "时点", "交付内容"], ms_rows, [0.10, 0.22, 0.68],
                        col_styles=[tc_c, tc_c, tc]))
story.append(Spacer(1, 10))

# ══ 二、里程碑详解 ══
story.append(CondPageBreak(6 * cm))
story.append(Paragraph("二、里程碑详解", h1))

def ms_section(tag, title, deliver, basis, accept):
    els = [Paragraph("%s · %s" % (tag, title), h2)]
    els.append(Paragraph("交付内容", h3))
    for i, d in enumerate(deliver, 1):
        els.append(Paragraph("%d. %s" % (i, d), bullet))
    els.append(Paragraph("排期依据", h3))
    els.append(Paragraph(basis, body))
    els.append(Paragraph("验收标准", h3))
    els.append(Paragraph(accept, body))
    story.extend(safe_keep_together(els))
    story.append(Spacer(1, 6))

ms_section("M1", "9/9：配置中心上线 + 发布链前置修复",
    ["Milvus Lite close 死锁修复：数据构建收尾阶段的已知阻塞，是后续所有数据发布功能的技术前置；完成当天以一次完整数据构建验证。",
     "配置中心（管理区新页面，需登录）：系统状态面板（当前服务包版本、发布时间、绑定版本号、存储健康、纠错与手工召回计数、磁盘余量）；数据新鲜度面板（四个数据域各自上次成功采集时间与距今间隔，与当前服务包构建时间并排展示）；采集配置（各域采集开关、每轮调用配额上限、执行时间窗口）；外部服务 key 健康检查（搜索、学术 API、本地大模型、重排模型一键探测连通性，页面仅显示 key 尾号，不显示明文）。"],
    "风险前置——发布链上最大的阻塞最先排除；配置中心是后续所有管理页面的公共壳。",
    "页面信息与系统实际状态一致；原状态接口 500 缺陷消失；配置修改落库、服务重启后保留、有审计记录；一次完整构建收尾不挂起。")

ms_section("M2", "9/11：任务运行面 + 用户会话审计增强",
    ["任务运行面：全部采集任务的清单与下次自动运行时间、历史记录（成功、失败、耗时、处理条数）、失败红点告警；按任务“立即采集”按钮——与定时任务执行同一套闸门（防重复锁、配额上限、熔断状态），手动触发不绕过任何限制；任务运维动作（Milvus 向量回填、检索效果验证）。",
     "用户会话审计增强（扩展现有访问日志页）：身份维度（记录提问者身份，登录用户记账号、公开访问记匿名，不记录 IP）；组合筛选（时间范围 × 问题类型（A–G）× 身份 × 状态）；导出（按当前筛选条件导出 CSV/JSONL）；概览统计（每日会话数与轮次数、问题类型分布、错误率、热门提问排行）。"],
    "任务面复用 M1 建立的页面壳与配置存储；会话审计与采集线无依赖，双线并行完成。",
    "手动触发任务成功并进入历史，运行中重复触发被拒绝并提示；筛选、导出、统计结果与数据库对账一致；旧数据无损升级（历史记录身份为空显示匿名）。")

ms_section("M3", "9/15：周期采集试运行 + 数据导入正门",
    ["周期采集：定时任务上线——企业新闻、官网产品重抓（每周），论文元数据回填（每周），教授主页与论文专利增量（每月）；全部限定夜间窗口执行，每轮设调用配额上限，连续失败自动熔断停跑。",
     "数据导入正门（恢复网页入口，此前仅命令行）：页面上传企业、专利 Excel 表格（自动查重，同文件重复上传拒绝；导入预检；企业数据自动进入富化流水线，补全产品、新闻、融资信息）；教授采集源管理（名单增删改查 + 触发抓取，全量、抽样、预览三种模式）。"],
    "上传链在新环境下的适配是本计划最大的技术不确定点，安排在窗口前段（9/12 前）完成技术验证，验证通过后收尾界面。",
    "试运行模式——缩短触发间隔自动运行不少于 2 次 + 手动触发各 1 次均成功；一次企业表格从上传到富化完成、数据库产生增量全链走通；正式周、月节奏同步上线，长期运行表现延伸至交付后持续观察（任务面板可见）。")

ms_section("M4", "9/17：管理面收官 + 首次一键发布演练",
    ["管理面收官：质量问题处理页（列表、解决、原始数据预览）；教授工作台动作（确认就绪、送审、标记重爬，与评审台流程衔接）；旧 React 管理前端正式退役——其全部能力已由新管理面承接，双前端并存问题就此收口。",
     "首次一键发布演练：“立即发布”按钮触发完整发布链——重建数据包、自举校验、7 个真实会话回放回归（确保新数据不引入回答错误）、备份门禁、原子切换、秒级重启、冒烟检查，任一步失败自动回切旧版本。窗口内完成一次真实发布和一次回滚演练。"],
    "发布演练依赖 M1 的死锁修复与 M3 产生的采集增量；管理面收官依赖 M2 的任务面基建。",
    "真实发布端到端成功，问答服务中断不超过重启时长（秒级）；回滚演练成功恢复旧版本；旧前端下线后无引用残留、线上功能不受影响。")

ms_section("M5", "9/21：端到端验收 + 交付物",
    ["端到端验收：走一次真实全链——采集产生新数据、一键发布新数据包、在对话入口检索到该新数据，验证闭环成立。",
     "交付物：运维手册（日常巡检、发布、回滚、故障恢复流程）；客户现场迁移方案后半段素材（密钥与启动参数、首启冒烟、反向代理发布、守护与日常运维、回退预案）。"],
    "全部功能切片完成后合流收尾，端到端演练同时充当整体回归。",
    "端到端链路走通；文档与系统实际状态一致；数据恢复流程演练一次成功。")

# ══ 三、执行前提与风险 ══
story.append(CondPageBreak(6 * cm))
story.append(Paragraph("三、执行前提与风险", h1))
risk_rows = [
    ["1", "双线并行是硬前提", "全部工作量约 15–16 人日，两条线各一名执行者方可两周完成；单线不可行（备选：三周，或裁减质量问题页与审计统计两块）"],
    ["2", "周期采集验收口径", "两周窗口内等不到自然周、月周期，以试运行模式验收（缩短间隔自动触发 + 手动触发）；正式节奏同步上线，观察期延伸至交付后"],
    ["3", "最大技术不确定点", "上传导入链在新运行环境下的适配，9/12 前出结论；若不通，降级方案为保留命令行导入 + 简化状态页，完整链路顺延"],
    ["4", "死锁修复超期预案", "若超 2 个工作日，发布演练（M4 后半）顺延，其余交付不受影响"],
    ["5", "缓冲", "仅最后半天为缓冲；任一切片超期首先压缩端到端演练与文档，其次顺延 M4、M5"],
]
story.append(Spacer(1, 6))
story.append(make_table(["#", "事项", "说明"], risk_rows, [0.06, 0.22, 0.72],
                        col_styles=[tc_c, tc, tc]))
story.append(Spacer(1, 10))

# ══ 附：双线逐日日历 ══
story.append(CondPageBreak(7 * cm))
story.append(Paragraph("附：双线逐日日历", h1))
cal_rows = [
    ["D1 9/8", "W1：配置中心页面 + 状态接口修复定位", "P0：Milvus 死锁定位"],
    ["D2 9/9", "W1：配置接口 + key 健康 → W1 验收（M1）", "P0：修复 + 完整构建验证 → P0 验收（M1）"],
    ["D3 9/10", "W2：任务接口 + 防重复锁", "W5：身份字段迁移 + 组合筛选"],
    ["D4 9/11", "W2：运行历史、立即采集、任务运维 → W2 验收（M2）", "W5：导出 + 统计 → W5 验收（M2）"],
    ["D5 9/14", "W3：上传链适配（技术验证点，当日出结论）", "W6：定时任务声明 + 配额、熔断接线"],
    ["D6 9/15", "W3：上传页 + 批次跟踪", "W6：试运行自动触发验证 → W6 验收（M3）"],
    ["D7 9/16", "W3：seed 管理 → W3 验收（M3）", "W7：发布脚本链路组装"],
    ["D8 9/17", "W4：质量问题页 + 工作台 + 旧前端退役 → W4 验收（M4）", "W7：真实发布演练 + 回滚演练 → W7 验收（M4）"],
    ["D9 9/18", "W8：运维手册 + 迁移素材 + 端到端演练（双线合流）", "同左"],
    ["D10 9/21", "W8：验收报告 + 缓冲 → W8 验收（M5）", "同左"],
]
story.append(Spacer(1, 6))
story.append(make_table(["日", "A 线（管理面 / 数据面）", "B 线（管道 / 审计）"], cal_rows,
                        [0.15, 0.425, 0.425], col_styles=[tc_c, tc, tc]))

doc = SimpleDocTemplate(
    BODY_PDF, pagesize=A4,
    leftMargin=LM, rightMargin=RM, topMargin=TM, bottomMargin=BM,
    title="系统收尾两周交付计划", author="Z.ai", creator="Z.ai",
    subject="科创数据平台系统收尾两周交付计划（里程碑 M1-M5）",
)
doc.build(story, onFirstPage=page_deco, onLaterPages=page_deco)
print("body ok:", BODY_PDF)

# ── Cover (template 03 Monolith, proposal/plan) ──
from cover_render import render_cover, detect_fonts
cover_content = {
    "kicker": "科创数据平台 · 系统收尾专项",
    "hero": "系统收尾两周交付计划",
    "summary": "覆盖管理配置中心、数据管理操作面、周期数据采集与发布、用户会话审计四大板块；9 月 8 日开工、9 月 21 日完成，共 10 个工作日，五个里程碑逐项交付、逐项验收。",
    "meta": "2026 年 9 月",
    "footer": "SYSTEM WRAP-UP DELIVERY PLAN",
}
cover_palette = {"primary": "#278eb0", "text": "#1d1f20", "muted": "#6e767a", "bg": "#ffffff"}
render_cover("03", cover_content, COVER_PDF, palette=cover_palette, fonts=detect_fonts())
print("cover ok:", COVER_PDF)

# ── Merge cover + body ──
from pypdf import PdfReader, PdfWriter
A4_W, A4_H = 595.28, 841.89

def normalize(page):
    w, h = float(page.mediabox.width), float(page.mediabox.height)
    if abs(w - A4_W) > 2 or abs(h - A4_H) > 2:
        from pypdf import Transformation
        page.add_transformation(Transformation().scale(sx=A4_W / w, sy=A4_H / h))
        page.mediabox.lower_left = (0, 0)
        page.mediabox.upper_right = (A4_W, A4_H)
    return page

writer = PdfWriter()
writer.add_page(normalize(PdfReader(COVER_PDF).pages[0]))
for p in PdfReader(BODY_PDF).pages:
    writer.add_page(normalize(p))
writer.add_metadata({
    "/Title": "系统收尾两周交付计划",
    "/Author": "Z.ai", "/Creator": "Z.ai",
    "/Subject": "科创数据平台系统收尾两周交付计划（里程碑 M1-M5）",
})
with open(FINAL_PDF, "wb") as f:
    writer.write(f)
print("final ok:", FINAL_PDF)
