"""Calibration probe for the embedding identity check (#3).

Three endpoints, one production code path
(``backend.services.canonical_v2_embedding_identity.verify_embedding_identity``):

1. the real school endpoint (``100.64.0.27:18005``, the model the index was built
   with) — no local server;
2. a local **gateway** that forwards to the real endpoint: same model, another
   address (the "customer's own gateway in front of the same model" case);
3. a local **wrong-space** endpoint that answers 200 with 4096 floats produced by
   the repository's own token-hash embedding algorithm
   (``index_projection_isolated.RecordedEmbeddingAdapter``,
   ``canonical-v2-token-hash-l2-v1``): right dimension, wrong space. No second
   embedding *model* is reachable from this box (18005 serves
   ``Qwen/Qwen3-Embedding-8B`` only, 18006 serves the reranker), so this is the
   stand-in for "a different model behind the same protocol"; it is generated by
   the same code the repo uses for its recorded embeddings, and it is exactly the
   failure mode that must be rejected (200 + dimension 4096 + not the index's
   space).

The credential is read through ``load_local_api_key()`` and never printed.

Usage:
  CANONICAL_V2_SERVING_PACK=<pack> uv run python probe_embedding_identity_calibration.py \
      --out .agents/runs/embedding-endpoint-configurable-and-lane-fail-open/probe/identity-calibration.json
"""

from __future__ import annotations

import argparse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import json
from pathlib import Path
import sys
import threading
from typing import Any
import urllib.request

REPO_ROOT = Path(__file__).resolve().parents[3]
ADMIN_ROOT = REPO_ROOT / "apps" / "admin-console"
AGENT_ROOT = REPO_ROOT / "apps" / "miroflow-agent"
for root in (ADMIN_ROOT, AGENT_ROOT):
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))

from backend.services.canonical_v2_embedding_identity import (  # noqa: E402
    verify_embedding_identity,
)
from src.data_agents.canonical_v2.index_projection_isolated import (  # noqa: E402
    RecordedEmbeddingAdapter,
)
from src.data_agents.providers.local_api_key import load_local_api_key  # noqa: E402

REAL_BASE_URL = "http://100.64.0.27:18005/v1"
MODEL = "Qwen/Qwen3-Embedding-8B"
DIMENSION = 4096


class _GatewayServer:
    """One loopback endpoint in one of two modes: proxy or wrong-space."""

    def __init__(self, mode: str) -> None:
        self.mode = mode
        self.requests: list[dict[str, Any]] = []
        self._api_key = load_local_api_key()
        self._hash_adapter = RecordedEmbeddingAdapter(
            model_id=MODEL, dimension=DIMENSION
        )
        outer = self

        class Handler(BaseHTTPRequestHandler):
            def do_POST(self) -> None:  # noqa: N802 - handler API
                length = int(self.headers.get("Content-Length", "0"))
                payload = json.loads(self.rfile.read(length) or b"{}")
                outer.requests.append({"path": self.path, "bytes": length})
                if outer.mode == "proxy":
                    body = outer._proxy(payload)
                else:
                    texts = payload.get("input") or []
                    if isinstance(texts, str):
                        texts = [texts]
                    vectors = outer._hash_adapter.embed_batch(tuple(texts))
                    body = json.dumps(
                        {
                            "data": [
                                {"index": index, "embedding": list(vector)}
                                for index, vector in enumerate(vectors)
                            ]
                        }
                    ).encode()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)

            def log_message(self, *_: object) -> None:
                return

        self._server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
        self._thread = threading.Thread(target=self._server.serve_forever, daemon=True)
        self._thread.start()

    def _proxy(self, payload: dict[str, Any]) -> bytes:
        request = urllib.request.Request(
            f"{REAL_BASE_URL}/embeddings",
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self._api_key}",
            },
            method="POST",
        )
        with urllib.request.urlopen(request, timeout=30) as response:
            return response.read()

    @property
    def base_url(self) -> str:
        return f"http://127.0.0.1:{self._server.server_port}/v1"

    def close(self) -> None:
        self._server.shutdown()
        self._server.server_close()


def _record(report: Any) -> dict[str, Any]:
    return report.as_dict()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    api_key = load_local_api_key()
    print("credential loaded:", bool(api_key))

    results: dict[str, Any] = {}
    gateway = _GatewayServer("proxy")
    wrong = _GatewayServer("hash")
    try:
        results["real_index_arm"] = {
            "configured": REAL_BASE_URL,
            "expected_arm": "index",
            "report": _record(
                verify_embedding_identity(
                    configured_base_url=REAL_BASE_URL, api_key=api_key
                )
            ),
        }
        results["gateway_reference_arm"] = {
            "configured": gateway.base_url,
            "recorded": REAL_BASE_URL,
            "expected_arm": "reference",
            "report": _record(
                verify_embedding_identity(
                    configured_base_url=gateway.base_url,
                    recorded_base_url=REAL_BASE_URL,
                    api_key=api_key,
                )
            ),
        }
        results["wrong_space_reference_arm"] = {
            "configured": wrong.base_url,
            "recorded": REAL_BASE_URL,
            "expected_arm": "reference",
            "report": _record(
                verify_embedding_identity(
                    configured_base_url=wrong.base_url,
                    recorded_base_url=REAL_BASE_URL,
                    api_key=api_key,
                )
            ),
        }
        results["wrong_space_index_arm"] = {
            "configured": wrong.base_url,
            "expected_arm": "index",
            "report": _record(
                verify_embedding_identity(
                    configured_base_url=wrong.base_url,
                    # recorded == configured forces the index arm: this is the
                    # "no reference endpoint" case the arm exists for.
                    recorded_base_url=wrong.base_url,
                    api_key=api_key,
                )
            ),
        }
    finally:
        gateway.close()
        wrong.close()

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(results, ensure_ascii=False, indent=2), encoding="utf-8")
    for name, entry in results.items():
        report = entry["report"]
        print(
            f"{name}: arm={report['arm']} passed={report['passed']} "
            f"cos={report['cosine']} threshold={report['threshold']} "
            f"checks={report['checks']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
